export const Brand = {
  primary: '#1A56DB',
  primaryDark: '#0E3A9F',
  primaryLight: '#3B82F6',
  accent: '#F97316',
  accentDark: '#EA580C',
  accentLight: '#FB923C',
  success: '#22C55E',
  warning: '#EAB308',
  error: '#EF4444',
  white: '#FFFFFF',
  black: '#0A0F1E',
};

export const Colors = {
  light: {
    text: '#0A0F1E',
    subtext: '#6B7280',
    background: '#F1F5FF',
    card: '#FFFFFF',
    border: '#E2E8F0',
    tint: Brand.primary,
    icon: '#6B7280',
    tabIconDefault: '#9CA3AF',
    tabIconSelected: Brand.primary,
    tabBar: '#FFFFFF',
  },
  dark: {
    text: '#F1F5FF',
    subtext: '#9CA3AF',
    background: '#060C1A',
    card: '#0D1730',
    border: '#1E2A45',
    tint: Brand.primaryLight,
    icon: '#9CA3AF',
    tabIconDefault: '#4B5563',
    tabIconSelected: Brand.primaryLight,
    tabBar: '#0D1730',
  },
};
